version: "3.2"

services:

  frontend_common:
    build: .
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      # - /app/node_modules
      - ./:/app
    ports:
      - 80:3000
       
    

